#!/usr/bin/env bash
# last_verified: 2026-08-18 · terraform n/a
#
# network-topology-terraform.sh — render a small network topology as Terraform
# HCL (one VPC, a configurable number of subnets, an internet gateway, and a
# default route), driven entirely by parameters.
#
# This is the IaC + Networking pattern in miniature: the network is described
# declaratively in code, and the same script shapes every environment, only
# with different parameter values.

set -euo pipefail

NET_NAME="${1:-demo}"
VPC_CIDR="${2:-10.0.0.0/16}"
SUBNET_COUNT="${3:-2}"
OUT_DIR="${4:-generated-network}"

if [[ ! "$SUBNET_COUNT" =~ ^[1-9][0-9]*$ ]]; then
    echo "error: subnet count must be a positive integer (got '$SUBNET_COUNT')" >&2
    exit 1
fi

# Work out how many extra bits cidrsubnet() needs so we can carve SUBNET_COUNT
# subnets out of the VPC CIDR. 2^newbits >= SUBNET_COUNT keeps every subnet
# non-overlapping.
newbits=0
pow=1
while (( pow < SUBNET_COUNT )); do
    newbits=$((newbits + 1))
    pow=$((pow * 2))
done

mkdir -p "$OUT_DIR"
TF_FILE="${OUT_DIR}/network.tf"

{
    echo "# Generated by network-topology-terraform.sh"
    echo ""
    echo 'resource "aws_vpc" "main" {'
    echo "  cidr_block = \"${VPC_CIDR}\""
    echo '  tags = { Name = "'"${NET_NAME}"'" }'
    echo '}'
    echo ""
    echo 'resource "aws_internet_gateway" "gw" {'
    echo '  vpc_id = aws_vpc.main.id'
    echo '  tags   = { Name = "'"${NET_NAME}"'-gw" }'
    echo '}'
    echo ""
    for ((i = 0; i < SUBNET_COUNT; i++)); do
        echo "resource \"aws_subnet\" \"subnet_${i}\" {"
        echo "  vpc_id     = aws_vpc.main.id"
        echo "  cidr_block = cidrsubnet(\"${VPC_CIDR}\", ${newbits}, ${i})"
        echo '  tags       = { Name = "'"${NET_NAME}"'-subnet-'"${i}"'" }'
        echo '}'
        echo ""
    done
    echo 'resource "aws_route_table" "main" {'
    echo '  vpc_id = aws_vpc.main.id'
    echo '  tags   = { Name = "'"${NET_NAME}"'-rt" }'
    echo '}'
    echo ""
    echo 'resource "aws_route" "default_route" {'
    echo '  route_table_id         = aws_route_table.main.id'
    echo '  destination_cidr_block = "0.0.0.0/0"'
    echo '  gateway_id             = aws_internet_gateway.gw.id'
    echo '}'
} > "$TF_FILE"

echo "wrote ${TF_FILE} with ${SUBNET_COUNT} subnet(s) carved from ${VPC_CIDR}"
echo "apply it in a real network by running terraform plan/apply inside ${OUT_DIR}"
